pipeline {
    agent any

    environment {
        IMAGE_NAME = "movie-app"
        CONTAINER_NAME = "movie-container"
        PORT = "3000"
        VITE_OMDB_API_KEY = "cd8d328"
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('movie') {
                    sh 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('movie') {
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('movie') {
                    sh """
                        docker build \
                        --build-arg VITE_OMDB_API_KEY=${VITE_OMDB_API_KEY} \
                        -t ${IMAGE_NAME}:latest .
                    """
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker stop ${CONTAINER_NAME} || true'
                sh 'docker rm ${CONTAINER_NAME} || true'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh """
                    docker run -d \
                    -p ${PORT}:3000 \
                    --name ${CONTAINER_NAME} \
                    --restart unless-stopped \
                    ${IMAGE_NAME}:latest
                """
            }
        }

        stage('Health Check') {
            steps {
                sh 'sleep 10'
                sh 'curl -f http://localhost:${PORT} || exit 1'
            }
        }
    }

    post {

        success {
            echo '✅ Deployment Successful!'
            echo '🌐 Application URL: http://13.232.217.251:3000'
        }

        failure {
            echo '❌ Pipeline Failed!'
        }

        always {
            sh 'docker image prune -f || true'
        }
    }
}